# Generated by Django 5.2 on 2025-04-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_token_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
